In [4]:
import pandas as pd
from pathlib import Path

path = Path("Data19to23")

all_files = sorted(path.glob("*.csv"))

li = []

for filename in all_files:
    df = pd.read_csv(filename, sep=";", index_col=None, header=0)
    df['Patient_ID'] = filename.stem
    li.append(df)

combined_activity = pd.concat(li, axis=0, ignore_index=True)
combined_activity.to_csv("Combined_Datasets_19to23.csv", index=False)

In [5]:
df.head(6)

,time,glucose,calories,heart_rate,steps,basal_rate,bolus_volume_delivered,carb_input,Patient_ID
0,2020-01-17T00:00:00,40.000000,15.0429,96.371901,8.0,0.035,0.0,1.0,HUPA0023P
1,2020-01-17T00:05:00,41.333333,8.3164,91.395349,0.0,0.035,0.0,0.0,HUPA0023P
2,2020-01-17T00:10:00,42.666667,7.5826,85.991935,0.0,0.035,0.0,0.0,HUPA0023P
3,2020-01-17T00:15:00,44.000000,7.3380,82.434426,0.0,0.035,0.0,0.0,HUPA0023P
4,2020-01-17T00:20:00,50.000000,7.5826,78.822581,0.0,0.035,0.0,0.0,HUPA0023P
5,2020-01-17T00:25:00,56.000000,7.5826,81.101562,0.0,0.035,0.0,0.0,HUPA0023P

In [6]:
df.shape

(3919, 9)

In [8]:
df['time'] = pd.to_datetime(df['time'])

In [10]:
cols_to_round = ["glucose", "calories", "heart_rate"]

df[cols_to_round] = df[cols_to_round].round(3)

In [11]:
df.head()

,time,glucose,calories,heart_rate,steps,basal_rate,bolus_volume_delivered,carb_input,Patient_ID
0,2020-01-17 00:00:00,40.000,15.043,96.372,8.0,0.035,0.0,1.0,HUPA0023P
1,2020-01-17 00:05:00,41.333,8.316,91.395,0.0,0.035,0.0,0.0,HUPA0023P
2,2020-01-17 00:10:00,42.667,7.583,85.992,0.0,0.035,0.0,0.0,HUPA0023P
3,2020-01-17 00:15:00,44.000,7.338,82.434,0.0,0.035,0.0,0.0,HUPA0023P
4,2020-01-17 00:20:00,50.000,7.583,78.823,0.0,0.035,0.0,0.0,HUPA0023P

In [12]:
numeric_cols = [
    'glucose',
    'calories',
    'heart_rate',
    'steps',
    'basal_rate',
    'bolus_volume_delivered',
    'carb_input'
]

# Compute IQR
Q1 = df[numeric_cols].quantile(0.25)
Q3 = df[numeric_cols].quantile(0.75)
IQR = Q3 - Q1

# Outlier mask (DataFrame of True/False)
outliers = (df[numeric_cols] < (Q1 - 1.5 * IQR)) | \
           (df[numeric_cols] > (Q3 + 1.5 * IQR))

# Count outliers per column
outliers.sum()

glucose                    12
calories                  396
heart_rate                 51
steps                     851
basal_rate                384
bolus_volume_delivered     40
carb_input                 63
dtype: int64

In [13]:
df.head(3)

,time,glucose,calories,heart_rate,steps,basal_rate,bolus_volume_delivered,carb_input,Patient_ID
0,2020-01-17 00:00:00,40.000,15.043,96.372,8.0,0.035,0.0,1.0,HUPA0023P
1,2020-01-17 00:05:00,41.333,8.316,91.395,0.0,0.035,0.0,0.0,HUPA0023P
2,2020-01-17 00:10:00,42.667,7.583,85.992,0.0,0.035,0.0,0.0,HUPA0023P